Feature/Update Repo
bernardopires/twitch-chat-logger pull request #8
Opened 2017-01-30 19:00 UTC by juanpflores

Hey @bernardopires,
Great Repo! I added the next changes to the repo in order to allow it to work with the new Auth system for the Twitch API:

- Added the API Dictionary in the settings file.
- Send the API key via headers when you request the top 100 streamers. 
- Added necessary documentation on the README file.

It's working on my computer. Let me know if you need me to make any changes.

2017-01-30 22:02 UTC, bernardopires requested changes
Awesome, thanks for the patch! Please add these little comments and we're good to go. Thanks for fixing this!

2017-01-30 22:02 UTC, bernardopires commented on settings.py.example
> +    'PASSWORD': 'PASSWORD',
Is the format no longer oauth? Please add a comment saying which format is expected. Thanks!

2017-01-30 22:02 UTC, bernardopires commented on settings.py.example
> +	'CLIENTID': YOUR_CLIENT_ID
Please add quotes if it's a string and add which format is expected (or where to get it from)

2017-01-31 02:57 UTC, juanpflores commented on settings.py.example
> +    'PASSWORD': 'PASSWORD',
You're absolutely right.

2017-01-31 03:02 UTC, juanpflores commented
@bernardopires I've finished the changes on the Pull Request

2017-02-10 16:40 UTC, juanpflores commented
Hey @bernardopires!
Any updates on this PR?

2017-02-10 23:02 UTC, bernardopires approved these changes

2017-02-10 23:02 UTC, merged

2017-02-10 23:02 UTC, bernardopires commented
Oops, sorry, forgot to re-review your code. Thanks for the patch!